// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR0Gq3HwrAfHFfQo8ngrLFNo7YBSLpw5U',
    appId: '1:1028791528109:web:709dc56fec1446e5bef424',
    messagingSenderId: '1028791528109',
    projectId: 'djvmf-ce8e6',
    authDomain: 'djvmf-ce8e6.firebaseapp.com',
    storageBucket: 'djvmf-ce8e6.firebasestorage.app',
    measurementId: 'G-6VQSNE9DQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_11GJSyyw9ollalFv91DT62_sTZ35SQ',
    appId: '1:1028791528109:android:8bf3f45be42b4b6dbef424',
    messagingSenderId: '1028791528109',
    projectId: 'djvmf-ce8e6',
    storageBucket: 'djvmf-ce8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq_IPBzPZ70RW4M6RNmbP1VrE3YSr4B7Q',
    appId: '1:1028791528109:ios:4b6669244d034d31bef424',
    messagingSenderId: '1028791528109',
    projectId: 'djvmf-ce8e6',
    storageBucket: 'djvmf-ce8e6.firebasestorage.app',
    iosBundleId: 'com.example.accessoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq_IPBzPZ70RW4M6RNmbP1VrE3YSr4B7Q',
    appId: '1:1028791528109:ios:4b6669244d034d31bef424',
    messagingSenderId: '1028791528109',
    projectId: 'djvmf-ce8e6',
    storageBucket: 'djvmf-ce8e6.firebasestorage.app',
    iosBundleId: 'com.example.accessoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR0Gq3HwrAfHFfQo8ngrLFNo7YBSLpw5U',
    appId: '1:1028791528109:web:fcee58a8d14f8a6bbef424',
    messagingSenderId: '1028791528109',
    projectId: 'djvmf-ce8e6',
    authDomain: 'djvmf-ce8e6.firebaseapp.com',
    storageBucket: 'djvmf-ce8e6.firebasestorage.app',
    measurementId: 'G-HEL34N7N3L',
  );
}
